OPENAI_API_KEY = "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"
ALPHA_VANTAGE_API_KEY = "QWFET177VDOFH8NQ"